export const INIT_MINES_GRID = 'INIT_MINES_GRID'
export const OPEN_CELL = 'OPEN_CELL'
export const FLAG_CELL = 'FLAG_CELL'
export const FLAG_TOGGLE = 'FLAG_TOGGLE'
export const SET_WINNER_TIME = 'SET_WINNER_TIME'

export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR'

export const POST_USER = 'POST_USER'
export const POST_USER_SUCCESS = 'POST_USER_SUCCESS'
export const POST_USER_ERROR = 'POST_USER_ERROR'

export const FETCH_RECORDS = 'FETCH_RECORDS'
export const FETCH_RECORDS_SUCCESS = 'FETCH_RECORDS_SUCCESS'
export const FETCH_RECORDS_ERROR = 'FETCH_RECORDS_ERROR'

export const PUT_RECORD = 'PUT_RECORD'
export const PUT_RECORD_SUCCESS = 'PUT_RECORD_SUCCESS'
export const PUT_RECORD_ERROR = 'PUT_RECORD_ERROR'